languageCode: "en-us"
title: "Hybrid.Network"
baseURL: "https://hybrid.network/"
pygmentsStyle: "monokai"
pygmentsUseClasses: true
MetaDataFormat: "yaml"
permalinks:
  post: /:year/:month/:title/

params:
  github: hybridnetwork
